dist: jammy

language: python

matrix:
  include:
    - python: 3.7
    - python: 3.8
    - python: 3.9
    - python: 3.10

cache: pip

install:
# - sudo apt-get update
- sudo apt-get install pandoc
- pip install pypandoc
- pip install setuptools=="60.8.2"

script:
- make all

before_deploy:
- nvm install 18
- node --version
- npm --version
- npm install
- pip install bump2version

deploy:
- provider: script
  script: npm run semantic-release
  skip_cleanup: true
  on:
    python: '3.7'
    branch: main

- provider: pypi
  setuptools_version: "60.8.2"
  user: __token__
  password: $PYPI_TOKEN
  repository: https://upload.pypi.org/legacy
  skip_cleanup: true
  on:
    python: '3.7'
    tags: true
