language: python

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8

dist: xenial

cache: pip

before_install:
- npm install npm@latest -g
- sudo apt-get update
- sudo apt-get install pandoc
- pip install pypandoc
# - '[ "${TRAVIS_PULL_REQUEST}" == "false" ] && openssl aes-256-cbc -K $ghost_key -iv $ghost_iv -in .ghostenv.enc -out .ghostenv -d || true'

install:
- pip install tox-travis

script:
- tox

before_deploy:
- pip install bump2version
- nvm install 12
- npm install @semantic-release/changelog
- npm install @semantic-release/exec
- npm install @semantic-release/git
- npm install @semantic-release/github

deploy:
- provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    python: '3.5'
    branch: master

# - provider: pypi
#   user: $PYPI_USER
#   password: $PYPI_PASSWORD
#   repository: https://upload.pypi.org/legacy
#   skip_cleanup: true
#   on:
#     python: '3.5'
#     tags: true
